### PR TITLE
fix leader-board for the clean DB

### LINKED ISSUE #182: After clearing all users, server returns only HTTP 500
**Describe the bug**
With no users, getting [this rollbar error](https://rollbar.com/vlabs/Venue/items/32/)

> DataError: division by zero
> CONTEXT:  SQL function "leader_board_data" statement 1

**To Reproduce**
1. Go to admin console
2. Click on Clear campaign data
3. Server completely broken
4. See error on Rollbar

**Expected behavior**
Should be 0 points awarded.

**Screenshots**
n/a

**Additional context**
It looks like 0 is passed as `total_points` to the stored function, and that is causing the error. The stored function should be updated to handle 0 points.

Blocked by Volentix/venue#138

### PR DESCRIPTION
**Pull request by alexdashkov**
Closes #182 
Changed a stored procedure. I can't just fix previous migration and keep 'the django way'  so I added a new one. 

You can check a current error but please do not merge it right now, I'll add a fix for the referrals to this migration.

### CODE REVIEW

**Comment by shawnlauzon** [comment]
This looks like a reasonable change (assuming that the only change from the previous migration was the addition of that CASE). You still have more work to do on it?

**Comment by alexdashkov** [comment]
It's good for this issue, but I don't want to copy/paste this migration one more time, so I'd prefer to make changes for the VTX tokens ('User with referrals shows 200 VTX on leaderboard') in the same PR.

**Comment by shawnlauzon** [comment]
So then this PR is blocked on Volentix/venue#138. I updated the waffle board to show this.

**Comment by alexdashkov** [comment]
It's okay, I've removed referrals from the leaderboard endpoint.

**Review by shawnlauzon — APPROVED** [review]

**Pull request merged**
