### PR TITLE
Rewrite leader board data view using SQL

### LINKED ISSUE #167: Rankings table seems to grow unbounded
**Describe the bug**
There is a massive number of rows in the rankings table.

**To Reproduce**
1. Go to admin console
2. Click on rankings
3. Scroll down to bottom
4. See number of entries

**Expected behavior**
I would expect the number to be lower, but it is also possible that this is OK. I would like some better understanding of why this is so large, and possibly some remediation.

**Screenshots**

image

**Additional context**

### PR DESCRIPTION
**Pull request by alexdashkov**
Closes  https://github.com/Volentix/venue/issues/119. 

Please be careful, I added PSQL functions, query time is reduced but some logic was moved to the Postgres site. 

Result before / after: 
```
GET /api/retrieve/leaderboard-data/ => generated 87044 bytes in 19534 msecs
GET /api/retrieve/leaderboard-data/ => generated 87051 bytes in 260 msecs
```
**UPDATED**:
Set correct issue link

### CODE REVIEW

**Comment by joemarct** [comment]
@alexdashkov I'm glad you have these SQL superpowers! It might indeed be difficult to follow but it's transparent since code is all there.

What I fail to see, however, is how this PR closes issue #167. I would have expected some kind of regular pruning of the records in the rankings table. Perhaps you're still working on it though, so I'll wait.

**Comment by alexdashkov** [comment]
@joemarct oh sorry, I set a wrong issue link. The correct one is https://github.com/Volentix/venue/issues/119.

**Comment by alexdashkov** [comment]
Should I remake this PR to the master branch too?

**Comment by joemarct** [comment]
Assuming that @realrhys is using this `performance-testing` branch anyway for load testing, I think we can continue adding commits to this branch as performance-related issues arise. We will only merge this once load testing is done. That's my take but I would wait for @realrhys and/or @shawn 's input on this.

**Comment by shawnlauzon** [comment]
@joemarct's suggestion sounds good to me.

**Pull request merged**
