### PR TITLE
Fix and improve improve circleci

### PR DESCRIPTION
**Pull request by alexdashkov**
**TLDR:**
- A full refactoring of a CircleCI config to avoid troubles with cache.
- Remove test that uses celery in async mode

### CI:
CircleCI has 3 jobs: tests, build, deploy
#### build_and_test (executes for each branch):
    It's a step that up a full environement and runs tests. Instead of docke venv is cached (3sec instead of 30)
#### build_image (executes only for the master):
    Build a docker image using cache from the latest pushed container.
#### deploy(executes only for the master):
    Deploy image from the previous step to the dev cluster

### CODE REVIEW

**Comment by shawnlauzon** [comment]
@alexdashkov It seems to be stuck waiting ...

**Comment by alexdashkov** [comment]
@shawnlauzon I separated `tests_and_build` to the different jobs `tests` and `build`. So this job doesn't exist anymore. I suppose that the github config should be changed.

**Comment by shawnlauzon** [comment]
@alexdashkov I just changed the expectations, and it still doesn't work. I just see that tests runs twice and build not at all

**Comment by shawnlauzon** [comment]
Thanks for that information @alexdashkov

**Pull request merged**
